---
title: "Read"
date: "`r Sys.Date()`"
runtime: shiny
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: hide
    number_sections: TRUE
---

# SET-UP

```{r markdown, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, message=F, warning=F, fig.align = "center", fig.width = 9, fig.height = 6)
options(width = 200)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
path= "S:/Pélagiques/Plancton/Relevés"


#warning!!!!! years is used to make the files. make sure years and wdlist correspond!!!
#year with a file in Rdata would not be reprocessed.
years=c(2013,2016:2019,2021:2023,2024)
wdlist= c(paste0(path,"/Relevé 2013/Données brutes Bionet/"),
         #paste0(path,"/Relevé 2014/Données brutes Bionet/"),
           #paste0(path,"/Relevé 2015/Bionet/"), # consercutive not in file name
           paste0(path,"/Relevé 2016/Bionet/"),
           paste0(path,"/Relevé 2017/Bionet/"),
           paste0(path,"/Relevé 2018/Bionet/"),
           paste0(path,"/Relevé 2019/Bionet/"),
           paste0(path,"/Relevé 2021/Bionet_corrigé/Bionet/"),
           paste0(path,"/Relevé 2022/IML-2022-024_juin/Bionet/"),
           paste0(path,"/Relevé 2023/IML2023-20_Juin/Bionet/"),
         paste0(path,"/Relevé 2024/IML2024-12_juin/Bionet/"))
   
```    

```{r code=readLines('0.0_settings.R')}
```

# Readbionet files

```{r biochemsp, message = F}

for(wd in wdlist){
year<- years[which(wdlist==wd)]
 if(!file.exists(paste0("Rdata/Bionet_data", year, ".Rdata"))){
# Set the directory and file filtering

bion <- list.files(wd, pattern = "CNV")
bion <- grep(bion, pattern = "vpr", value = TRUE, invert = TRUE, ignore.case = TRUE) # for 2023
bion <- grep(bion, pattern = "000.CNV", value = TRUE, invert = TRUE, ignore.case = TRUE)

# Set up parallel backend
plan(multisession) # You can also use multicore (on Unix-based systems) or other strategies

# Function to process each file
process_file <- function(file) {

   check <- read_table(paste0(wd, file), col_names = FALSE)

    test2<- check %>% 
  mutate_all(~str_locate(., "Profondeur"))
skip=which(!is.na(test2$X1[,"start"]))[3]
 
# Read the data table

  df <- fread(paste0(wd, file), skip=skip,encoding = "Latin-1")
  if(nrow(df) > 5){ 
  colsdf <- fread(paste0(wd, file), skip=skip+5, nrows=1, encoding = "Latin-1")
  if(ncol(colsdf)< ncol(df)) colsdf <- fread(paste0(wd, file), skip=skip+8, nrows=1, encoding = "Latin-1")
if(ncol(colsdf) < ncol(df)) colsdf <- fread(paste0(wd, file), skip=skip+9, nrows=1, encoding = "Latin-1")
if(ncol(colsdf)< ncol(df)) {colsdf <-  as.character(colsdf)
 colsdf<-  c(colsdf[1:which(colsdf=="Date")-1],"day", "month",  "year",colsdf[(which(colsdf=="Date")+1)], "Latitude", "latitude.min", "Longitude", "Longitude.min",colsdf[(which(grepl(colsdf, pattern="avire"))): length(colsdf)])
}
 # Set column names
 colnames(df) <-  as.character(colsdf)
 
  
  # Detect consecutive and assign station number
  df$consecutive <- substring(file, nchar(file) - 6, nchar(file) - 4)
  if(ncol(check)==5) {df$station <- as.numeric(check[5, 5])
  }else{df$station=NA}
  

  } else(df =data.table())
    return(df)
}

# Process files in parallel
results <- future_lapply(bion, process_file)
# Combine results if needed
combined_data <- rbindlist(results)

allbongs<- flag_cast(combined_data %>%  mutate(Profondeur=as.numeric(Profondeur)))

bongocgg<- allbongs[[1]] %>% ungroup() %>% 
  dplyr::group_by(consecutive,depth) %>% 
  dplyr::summarize( Volume= sum(Flow, na.rm=T)) %>% 
  dplyr::group_by(consecutive) %>% 
  dplyr::mutate(sumVol=sum(Volume),
                maxdepth=max(depth)) %>% 
  dplyr::mutate(`%Volume`=Volume/sumVol*100,
          `theoricalVolume` =sumVol/maxdepth,
          `%theoricalVolume`=Volume/theoricalVolume*100,
          catZ = if_else(depth > (maxdepth -10), "last10m",
                         if_else(depth <= 5, "0-5m",
                         if_else(depth >5 & depth <11, "5-10m", "midlayer"))))

bongostats = bongocgg %>% dplyr::group_by(consecutive, catZ) %>%  
 dplyr::summarize(`%Volume`=sum(Volume)/sum(theoricalVolume)*100) %>% 
  dplyr::mutate(flag_bongo = if_else(catZ=="0-5m" & `%Volume` < 65, 1,
                              if_else(`%Volume` < 90 & catZ !="0-5m", 1,0))) %>% 
  dplyr::select(-`%Volume`) %>% 
  tidyr::pivot_wider(names_from=catZ, values_from=flag_bongo, values_fill=0) %>% 
  dplyr::mutate(midlayer=tidyr::replace_na(midlayer, 0),
         sumflag= `0-5m`+`5-10m`+last10m+midlayer)  %>% 
  dplyr::filter(sumflag >0) %>%  dplyr::select(-sumflag) %>%  dplyr::arrange(desc(`0-5m`), desc(`5-10m`), desc(midlayer)) %>% dplyr::relocate(midlayer, .before="last10m")
  
bongodepth<- allbongs[[2]]

bongocast<- allbongs[[3]]

save(combined_data,bongocgg, bongostats,bongodepth,bongocast, file= paste0("Rdata/Bionet_data", year, ".Rdata"))
 }
}

```

# Plot bionet files

```{r plotfiles, message = F, echo=F}

 bongocgg_all<-  tibble()
 bongodepth_all<-   tibble()
 bongostats_all<-   tibble()
bongocast_all<-   tibble()
 years=c(2013,2016:2019,2021:2024)
for(y in years){
load(paste0("Rdata/Bionet_data", y, ".Rdata"))
 bongocgg_all<-  bind_rows(bongocgg_all, bongocgg %>%  mutate(year=y))
 bongodepth_all<-  bind_rows(bongodepth_all, bongodepth %>%  mutate(year=y))
 bongostats_all<-  bind_rows(bongostats_all, bongostats %>%  mutate(year=y))
 bongocast_all <-  bind_rows(bongocast_all, 
                            bongocast %>%
                              dplyr::mutate(year=y, 
                                          Chrono=as.integer(Chrono), 
                                                 VitesseD2=as.numeric(`V. Débit #2`)) %>% 
                              dplyr::select(Profondeur, Chrono,cast, consecutive,station, year, `VitesseD2`))
}
 
 
 bongodepth_flag<- bongodepth_all %>%  mutate(meanegg=100/meandepth,
                           maxegg=100/maxdepth,
                           diffegg= (meanegg-maxegg)/maxegg *100) %>% 
  filter(diffegg>5) %>%  mutate(depthflag=1) %>%  dplyr::select(year, consecutive, depthflag, diffegg, meandepth,maxdepth)
 
bongostats_depth<- full_join(bongostats_all, bongodepth_flag) %>%  mutate(depthflag = replace_na(depthflag, 0))
 
plot_volume(dataset=list(bongostats_depth,bongocgg_all, bongocast_all, bongodepth_all))



#get % volume par bin de 1m.
```