---
title: "Read"
date: "`r Sys.Date()`"
runtime: shiny
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: hide
    number_sections: TRUE
---

# SET-UP

```{r markdown, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, fig.align = "center", fig.width = 9, fig.height = 6)
options(width = 200)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

library(shiny)
#2021 prob;eme avec cnv

```    

```{r code=readLines('0.0_settings.R')}
```

# Readbionet files

```{r biochemsp, message = F, echo=F}

 bongocgg_all<-  tibble()
 bongodepth_all<-   tibble()
 bongostats_all<-   tibble()
bongocast_all<-   tibble()
 years=c(2013, 2016:2019,2021:2023)
for(y in years){
load(paste0("Rdata/Bionet_data", y, ".Rdata"))
 bongocgg_all<-  bind_rows(bongocgg_all, bongocgg %>%  mutate(year=y))
 bongodepth_all<-  bind_rows(bongodepth_all, bongodepth %>%  mutate(year=y))
 bongostats_all<-  bind_rows(bongostats_all, bongostats %>%  mutate(year=y))
bongocast_all <-  bind_rows(bongocast_all, bongocast %>%  mutate(year=y))
}
#utiliser combined data pour visualiser les cast.allbongs<- flag_cast(combined_data)
#utiliser bongostats pour faire une table
#utiliser bongo depth dans une autre fenêtre pour comparaer avec max depth

 
plot_volume(dataset=list( bongostats_all,bongocgg_all, bongocast_all, bongodepth_all,))


#get % volume par bin de 1m.
```

